# DAT210x - Programming with Python for DS

## Module2 - Lab4

Import and alias Pandas:

In [84]:
# .. your code here ..
import pandas as pd

Load up the table from the link, and extract the dataset out of it. If you're having issues with this, look carefully at the sample code provided in the reading:

In [85]:
# .. your code here ..
df = pd.read_html("http://www.espn.com/nhl/statistics/player/_/stat/points/sort/points/year/2015/seasontype/2")[0]
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
2,1,"Jamie Benn, LW",DAL,82,35,52,87,1,64,1.06,253,13.8,6,10,13,2,3
3,2,"John Tavares, C",NYI,82,38,48,86,5,46,1.05,278,13.7,8,13,18,0,1
4,3,"Sidney Crosby, C",PIT,77,28,56,84,5,47,1.09,237,11.8,3,10,21,0,0

In [86]:
df.columns = ['RK','PLAYER','TEAM','GP','G','A','PTS','+/-','PIM','PTS/G','SOG','PCT', 'GWG', 'PP_G','PP_A','SH_G','SH_A']
df.head()

,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,PP_G,PP_A,SH_G,SH_A
0,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
2,1,"Jamie Benn, LW",DAL,82,35,52,87,1,64,1.06,253,13.8,6,10,13,2,3
3,2,"John Tavares, C",NYI,82,38,48,86,5,46,1.05,278,13.7,8,13,18,0,1
4,3,"Sidney Crosby, C",PIT,77,28,56,84,5,47,1.09,237,11.8,3,10,21,0,0

In [87]:
df = df.iloc[2:]
df.head()

,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,PP_G,PP_A,SH_G,SH_A
2,1,"Jamie Benn, LW",DAL,82,35,52,87,1,64,1.06,253,13.8,6,10,13,2,3
3,2,"John Tavares, C",NYI,82,38,48,86,5,46,1.05,278,13.7,8,13,18,0,1
4,3,"Sidney Crosby, C",PIT,77,28,56,84,5,47,1.09,237,11.8,3,10,21,0,0
5,4,"Alex Ovechkin, LW",WSH,81,53,28,81,10,58,1.00,395,13.4,11,25,9,0,0
6,NaN,"Jakub Voracek, RW",PHI,82,22,59,81,1,78,0.99,221,10.0,3,11,22,0,0

Next up, rename the columns so that they are _similar_ to the column definitions provided to you on the website. Be careful and don't accidentally use any column names twice. If a column uses special characters, you can replace them with regular characters to make it easier to work with:

In [88]:
# .. your code here ..

Get rid of any row that has at least 4 NANs in it. That is, any rows that do not contain player points statistics:

In [89]:
# .. your code here ..

df = df.dropna(axis = 0, thresh = 4)
df.head()

#NHL_DataFrame = NHL_DataFrame.dropna(axis=0, thresh=4)

,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,PP_G,PP_A,SH_G,SH_A
2,1,"Jamie Benn, LW",DAL,82,35,52,87,1,64,1.06,253,13.8,6,10,13,2,3
3,2,"John Tavares, C",NYI,82,38,48,86,5,46,1.05,278,13.7,8,13,18,0,1
4,3,"Sidney Crosby, C",PIT,77,28,56,84,5,47,1.09,237,11.8,3,10,21,0,0
5,4,"Alex Ovechkin, LW",WSH,81,53,28,81,10,58,1.00,395,13.4,11,25,9,0,0
6,NaN,"Jakub Voracek, RW",PHI,82,22,59,81,1,78,0.99,221,10.0,3,11,22,0,0

At this point, look through your dataset by printing it. There probably still are some erroneous rows in there. What indexing command(s) will you use to select all rows EXCEPT those rows?

In [91]:
# .. your code here ..

df = df[df.RK != 'RK']

#df[df.name != 'Tina']

#df.drop(df.iloc[::11, :])

#df.iloc[::5, :]

print(df)

#NHL_DataFrame = NHL_DataFrame.drop(labels=['RK'], axis=1)

     RK                  PLAYER TEAM  GP   G   A PTS  +/- PIM PTS/G  SOG  \
2     1          Jamie Benn, LW  DAL  82  35  52  87    1  64  1.06  253
3     2         John Tavares, C  NYI  82  38  48  86    5  46  1.05  278
4     3        Sidney Crosby, C  PIT  77  28  56  84    5  47  1.09  237
5     4       Alex Ovechkin, LW  WSH  81  53  28  81   10  58  1.00  395
6   NaN       Jakub Voracek, RW  PHI  82  22  59  81    1  78  0.99  221
7     6    Nicklas Backstrom, C  WSH  82  18  60  78    5  40  0.95  153
8     7         Tyler Seguin, C  DAL  71  37  40  77   -1  20  1.08  280
9     8         Jiri Hudler, LW  CGY  78  31  45  76   17  14  0.97  158
10  NaN        Daniel Sedin, LW  VAN  82  20  56  76    5  18  0.93  226
11   10  Vladimir Tarasenko, RW  STL  77  37  36  73   27  31  0.95  264
14  NaN        Nick Foligno, LW  CBJ  79  31  42  73   16  50  0.92  182
15  NaN       Claude Giroux, LW  PHI  81  25  48  73   -3  36  0.90  279
16  NaN         Henrik Sedin, C  VAN  82  18  55  73   11  22  0.89  101
17   14       Steven Stamkos, C   TB  82  43  29  72    2  49  0.88  268
18  NaN        Tyler Johnson, C   TB  77  29  43  72   33  24  0.94  203
19   16        Ryan Johansen, C  CBJ  82  26  45  71   -6  40  0.87  202
20   17         Joe Pavelski, C   SJ  82  37  33  70   12  29  0.85  261
21  NaN        Evgeni Malkin, C  PIT  69  28  42  70   -2  60  1.01  212
22  NaN         Ryan Getzlaf, C  ANA  77  25  45  70   15  62  0.91  191
23   20           Rick Nash, LW  NYR  79  42  27  69   29  36  0.87  304
26   21      Max Pacioretty, LW  MTL  80  37  30  67   38  32  0.84  302
27  NaN        Logan Couture, C   SJ  82  27  40  67   -6  12  0.82  263
28   23       Jonathan Toews, C  CHI  81  28  38  66   30  36  0.81  192
29  NaN        Erik Karlsson, D  OTT  82  21  45  66    7  42  0.80  292
30  NaN   Henrik Zetterberg, LW  DET  77  17  49  66   -6  32  0.86  227
31   26        Pavel Datsyuk, C  DET  63  26  39  65   12   8  1.03  165
32  NaN         Joe Thornton, C   SJ  78  16  49  65   -4  30  0.83  131
33   28     Nikita Kucherov, RW   TB  82  28  36  64   38  37  0.78  190
34  NaN        Patrick Kane, RW  CHI  61  27  37  64   10  10  1.05  186
35  NaN          Mark Stone, RW  OTT  80  26  38  64   21  14  0.80  157
38  NaN     Alexander Steen, LW  STL  74  24  40  64    8  33  0.86  223
39  NaN          Kyle Turris, C  OTT  82  24  40  64    5  36  0.78  215
40  NaN     Johnny Gaudreau, LW  CGY  80  24  40  64   11  14  0.80  167
41  NaN         Anze Kopitar, C   LA  79  16  48  64   -2  10  0.81  134
42   35        Radim Vrbata, RW  VAN  79  31  32  63    6  20  0.80  267
43  NaN      Jaden Schwartz, LW  STL  75  28  35  63   13  16  0.84  184
44  NaN      Filip Forsberg, LW  NSH  82  26  37  63   15  24  0.77  237
45  NaN       Jordan Eberle, RW  EDM  81  24  39  63  -16  24  0.78  183
46  NaN        Ondrej Palat, LW   TB  75  16  47  63   31  24  0.84  139
47   40         Zach Parise, LW  MIN  74  33  29  62   21  41  0.84  259

     PCT GWG PP_G PP_A SH_G SH_A
2   13.8   6   10   13    2    3
3   13.7   8   13   18    0    1
4   11.8   3   10   21    0    0
5   13.4  11   25    9    0    0
6   10.0   3   11   22    0    0
7   11.8   3    3   30    0    0
8   13.2   5   13   16    0    0
9   19.6   5    6   10    0    0
10   8.9   5    4   21    0    0
11  14.0   6    8   10    0    0
14  17.0   3   11   15    0    0
15   9.0   4   14   23    0    0
16  17.8   0    5   20    0    0
17  16.0   6   13   12    0    0
18  14.3   6    8    9    0    0
19  12.9   0    7   19    2    0
20  14.2   5   19   12    0    0
21  13.2   4    9   17    0    0
22  13.1   6    3   10    0    2
23  13.8   8    6    6    4    1
26  12.3  10    7    4    3    2
27  10.3   4    6   18    2    0
28  14.6   7    6   11    2    1
29   7.2   3    6   24    0    0
30   7.5   3    4   24    0    0
31  15.8   5    8   16    0    0
32  12.2   0    4   18    0    0
33  14.7   2    2   13    0    0
34  14.5   5    6   16    0    0
35  16.6   6    5    8    1    0
38  10.8   5    8   16    0    0
39  11.2   6    4   12    1    0
40  14.4   4    8   13    0    0
41  11.9   4    6   18    0    0
42  11.6   7   12   11    0    0
43  15.2   4    8    8    0    2
44  11.0   6    6   13    0    0
45  13.1   2    6   15    0    0
46  11.5   5    3    8    1    1
47  12.7   3   11    5    0    0

Get rid of the 'RK' column:

In [92]:
# .. your code here ..

df = df.drop("RK", axis = 1)
print(df)

#NHL_DataFrame = NHL_DataFrame.drop(labels=['RK'], axis=1)
#print (NHL_DataFrame)

                    PLAYER TEAM  GP   G   A PTS  +/- PIM PTS/G  SOG   PCT GWG  \
2           Jamie Benn, LW  DAL  82  35  52  87    1  64  1.06  253  13.8   6
3          John Tavares, C  NYI  82  38  48  86    5  46  1.05  278  13.7   8
4         Sidney Crosby, C  PIT  77  28  56  84    5  47  1.09  237  11.8   3
5        Alex Ovechkin, LW  WSH  81  53  28  81   10  58  1.00  395  13.4  11
6        Jakub Voracek, RW  PHI  82  22  59  81    1  78  0.99  221  10.0   3
7     Nicklas Backstrom, C  WSH  82  18  60  78    5  40  0.95  153  11.8   3
8          Tyler Seguin, C  DAL  71  37  40  77   -1  20  1.08  280  13.2   5
9          Jiri Hudler, LW  CGY  78  31  45  76   17  14  0.97  158  19.6   5
10        Daniel Sedin, LW  VAN  82  20  56  76    5  18  0.93  226   8.9   5
11  Vladimir Tarasenko, RW  STL  77  37  36  73   27  31  0.95  264  14.0   6
14        Nick Foligno, LW  CBJ  79  31  42  73   16  50  0.92  182  17.0   3
15       Claude Giroux, LW  PHI  81  25  48  73   -3  36  0.90  279   9.0   4
16         Henrik Sedin, C  VAN  82  18  55  73   11  22  0.89  101  17.8   0
17       Steven Stamkos, C   TB  82  43  29  72    2  49  0.88  268  16.0   6
18        Tyler Johnson, C   TB  77  29  43  72   33  24  0.94  203  14.3   6
19        Ryan Johansen, C  CBJ  82  26  45  71   -6  40  0.87  202  12.9   0
20         Joe Pavelski, C   SJ  82  37  33  70   12  29  0.85  261  14.2   5
21        Evgeni Malkin, C  PIT  69  28  42  70   -2  60  1.01  212  13.2   4
22         Ryan Getzlaf, C  ANA  77  25  45  70   15  62  0.91  191  13.1   6
23           Rick Nash, LW  NYR  79  42  27  69   29  36  0.87  304  13.8   8
26      Max Pacioretty, LW  MTL  80  37  30  67   38  32  0.84  302  12.3  10
27        Logan Couture, C   SJ  82  27  40  67   -6  12  0.82  263  10.3   4
28       Jonathan Toews, C  CHI  81  28  38  66   30  36  0.81  192  14.6   7
29        Erik Karlsson, D  OTT  82  21  45  66    7  42  0.80  292   7.2   3
30   Henrik Zetterberg, LW  DET  77  17  49  66   -6  32  0.86  227   7.5   3
31        Pavel Datsyuk, C  DET  63  26  39  65   12   8  1.03  165  15.8   5
32         Joe Thornton, C   SJ  78  16  49  65   -4  30  0.83  131  12.2   0
33     Nikita Kucherov, RW   TB  82  28  36  64   38  37  0.78  190  14.7   2
34        Patrick Kane, RW  CHI  61  27  37  64   10  10  1.05  186  14.5   5
35          Mark Stone, RW  OTT  80  26  38  64   21  14  0.80  157  16.6   6
38     Alexander Steen, LW  STL  74  24  40  64    8  33  0.86  223  10.8   5
39          Kyle Turris, C  OTT  82  24  40  64    5  36  0.78  215  11.2   6
40     Johnny Gaudreau, LW  CGY  80  24  40  64   11  14  0.80  167  14.4   4
41         Anze Kopitar, C   LA  79  16  48  64   -2  10  0.81  134  11.9   4
42        Radim Vrbata, RW  VAN  79  31  32  63    6  20  0.80  267  11.6   7
43      Jaden Schwartz, LW  STL  75  28  35  63   13  16  0.84  184  15.2   4
44      Filip Forsberg, LW  NSH  82  26  37  63   15  24  0.77  237  11.0   6
45       Jordan Eberle, RW  EDM  81  24  39  63  -16  24  0.78  183  13.1   2
46        Ondrej Palat, LW   TB  75  16  47  63   31  24  0.84  139  11.5   5
47         Zach Parise, LW  MIN  74  33  29  62   21  41  0.84  259  12.7   3

   PP_G PP_A SH_G SH_A
2    10   13    2    3
3    13   18    0    1
4    10   21    0    0
5    25    9    0    0
6    11   22    0    0
7     3   30    0    0
8    13   16    0    0
9     6   10    0    0
10    4   21    0    0
11    8   10    0    0
14   11   15    0    0
15   14   23    0    0
16    5   20    0    0
17   13   12    0    0
18    8    9    0    0
19    7   19    2    0
20   19   12    0    0
21    9   17    0    0
22    3   10    0    2
23    6    6    4    1
26    7    4    3    2
27    6   18    2    0
28    6   11    2    1
29    6   24    0    0
30    4   24    0    0
31    8   16    0    0
32    4   18    0    0
33    2   13    0    0
34    6   16    0    0
35    5    8    1    0
38    8   16    0    0
39    4   12    1    0
40    8   13    0    0
41    6   18    0    0
42   12   11    0    0
43    8    8    0    2
44    6   13    0    0
45    6   15    0    0
46    3    8    1    1
47   11    5    0    0

Make sure there are no holes in your index by resetting it. There is an example of this in the reading material. By the way, drop the original index.

In [96]:
# .. your code here ..

df = df.reset_index(drop = True)
print(df)
#NHL_DataFrame = NHL_DataFrame.reset_index(drop=True)

                    PLAYER TEAM  GP   G   A PTS  +/- PIM PTS/G  SOG   PCT GWG  \
0           Jamie Benn, LW  DAL  82  35  52  87    1  64  1.06  253  13.8   6
1          John Tavares, C  NYI  82  38  48  86    5  46  1.05  278  13.7   8
2         Sidney Crosby, C  PIT  77  28  56  84    5  47  1.09  237  11.8   3
3        Alex Ovechkin, LW  WSH  81  53  28  81   10  58  1.00  395  13.4  11
4        Jakub Voracek, RW  PHI  82  22  59  81    1  78  0.99  221  10.0   3
5     Nicklas Backstrom, C  WSH  82  18  60  78    5  40  0.95  153  11.8   3
6          Tyler Seguin, C  DAL  71  37  40  77   -1  20  1.08  280  13.2   5
7          Jiri Hudler, LW  CGY  78  31  45  76   17  14  0.97  158  19.6   5
8         Daniel Sedin, LW  VAN  82  20  56  76    5  18  0.93  226   8.9   5
9   Vladimir Tarasenko, RW  STL  77  37  36  73   27  31  0.95  264  14.0   6
10        Nick Foligno, LW  CBJ  79  31  42  73   16  50  0.92  182  17.0   3
11       Claude Giroux, LW  PHI  81  25  48  73   -3  36  0.90  279   9.0   4
12         Henrik Sedin, C  VAN  82  18  55  73   11  22  0.89  101  17.8   0
13       Steven Stamkos, C   TB  82  43  29  72    2  49  0.88  268  16.0   6
14        Tyler Johnson, C   TB  77  29  43  72   33  24  0.94  203  14.3   6
15        Ryan Johansen, C  CBJ  82  26  45  71   -6  40  0.87  202  12.9   0
16         Joe Pavelski, C   SJ  82  37  33  70   12  29  0.85  261  14.2   5
17        Evgeni Malkin, C  PIT  69  28  42  70   -2  60  1.01  212  13.2   4
18         Ryan Getzlaf, C  ANA  77  25  45  70   15  62  0.91  191  13.1   6
19           Rick Nash, LW  NYR  79  42  27  69   29  36  0.87  304  13.8   8
20      Max Pacioretty, LW  MTL  80  37  30  67   38  32  0.84  302  12.3  10
21        Logan Couture, C   SJ  82  27  40  67   -6  12  0.82  263  10.3   4
22       Jonathan Toews, C  CHI  81  28  38  66   30  36  0.81  192  14.6   7
23        Erik Karlsson, D  OTT  82  21  45  66    7  42  0.80  292   7.2   3
24   Henrik Zetterberg, LW  DET  77  17  49  66   -6  32  0.86  227   7.5   3
25        Pavel Datsyuk, C  DET  63  26  39  65   12   8  1.03  165  15.8   5
26         Joe Thornton, C   SJ  78  16  49  65   -4  30  0.83  131  12.2   0
27     Nikita Kucherov, RW   TB  82  28  36  64   38  37  0.78  190  14.7   2
28        Patrick Kane, RW  CHI  61  27  37  64   10  10  1.05  186  14.5   5
29          Mark Stone, RW  OTT  80  26  38  64   21  14  0.80  157  16.6   6
30     Alexander Steen, LW  STL  74  24  40  64    8  33  0.86  223  10.8   5
31          Kyle Turris, C  OTT  82  24  40  64    5  36  0.78  215  11.2   6
32     Johnny Gaudreau, LW  CGY  80  24  40  64   11  14  0.80  167  14.4   4
33         Anze Kopitar, C   LA  79  16  48  64   -2  10  0.81  134  11.9   4
34        Radim Vrbata, RW  VAN  79  31  32  63    6  20  0.80  267  11.6   7
35      Jaden Schwartz, LW  STL  75  28  35  63   13  16  0.84  184  15.2   4
36      Filip Forsberg, LW  NSH  82  26  37  63   15  24  0.77  237  11.0   6
37       Jordan Eberle, RW  EDM  81  24  39  63  -16  24  0.78  183  13.1   2
38        Ondrej Palat, LW   TB  75  16  47  63   31  24  0.84  139  11.5   5
39         Zach Parise, LW  MIN  74  33  29  62   21  41  0.84  259  12.7   3

   PP_G PP_A SH_G SH_A
0    10   13    2    3
1    13   18    0    1
2    10   21    0    0
3    25    9    0    0
4    11   22    0    0
5     3   30    0    0
6    13   16    0    0
7     6   10    0    0
8     4   21    0    0
9     8   10    0    0
10   11   15    0    0
11   14   23    0    0
12    5   20    0    0
13   13   12    0    0
14    8    9    0    0
15    7   19    2    0
16   19   12    0    0
17    9   17    0    0
18    3   10    0    2
19    6    6    4    1
20    7    4    3    2
21    6   18    2    0
22    6   11    2    1
23    6   24    0    0
24    4   24    0    0
25    8   16    0    0
26    4   18    0    0
27    2   13    0    0
28    6   16    0    0
29    5    8    1    0
30    8   16    0    0
31    4   12    1    0
32    8   13    0    0
33    6   18    0    0
34   12   11    0    0
35    8    8    0    2
36    6   13    0    0
37    6   15    0    0
38    3    8    1    1
39   11    5    0    0

Check the data type of all columns, and ensure those that should be numeric are numeric.

In [95]:
# .. your code here ..
df.dtypes

PLAYER    object
TEAM      object
GP        object
G         object
A         object
PTS       object
+/-       object
PIM       object
PTS/G     object
SOG       object
PCT       object
GWG       object
PP_G      object
PP_A      object
SH_G      object
SH_A      object
dtype: object

Your dataframe is now ready! Use the appropriate commands to answer the questions on the course lab page.

In [98]:
# .. your code here ..

#After completing the 6 steps above, how many rows remain in this dataset? (Not to be confused with the index!)
df.shape

(40, 16)

In [100]:
#How many unique PCT values exist in the table?

#df.PCT.value_counts()

df.PCT.nunique()
#df.domain.value_counts()

#df.domain.nunique()

36

In [110]:
#What is the value you get by adding the GP values at indices 15 and 16 of this table?

GP_15 = int(df.GP[15])
GP_16=int(df.GP[16])
GP_15+GP_16

164